service: template

plugins:
  - serverless-offline
  - serverless-plugin-typescript

custom:
  serverless-offline:
    port: 8000

provider:
  name: aws
  runtime: nodejs10.x
  stage: production
  memorySize: 128
  region: us-west-2
  environment:
    NODE_ENV: 'staging'

package:
  include:
    - config.*.js
  exclude:
    - node_modules/.bin/**
    - config.local.*
    - config.*.local.*

functions:
  index:
    handler: src/index.handler
    events:
      - http:
          path: /
          method: get
