service: text-my-wife

plugins:
  - serverless-offline
  - serverless-plugin-typescript

custom:
  serverless-offline:
    port: 8000
  message-bucket: ${file(./config.js):serverless.MESSAGE_BUCKET_NAME}

provider:
  name: aws
  runtime: nodejs10.x
  stage: production
  memorySize: 128
  region: us-west-2
  environment:
    NODE_ENV: 'production'
    TEXT_KEY: ${file(./config.js):serverless.TEXT_KEY}
    BUCKET_NAME: ${self:custom.message-bucket}
  iamRoleStatements:
    - Effect: 'Allow'
      Action: 'logs:*'
      Resource: '*'
    - Effect: 'Allow'
      Action: 'cloudwatch:*'
      Resource: '*'
    - Effect: 'Allow'
      Action: 's3:*'
      Resource: '*'

package:
  include:
    - config.js
  exclude:
    - node_modules/.bin/**


functions:
  index:
    handler: src/index.handler
    name: text-my-wife
    events:
      - schedule: cron(0 12 * * ? *)
resources: # CloudFormation template syntax
  Resources:
    messageBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.message-bucket}
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256